Bookstore: styling
Dorcas126/Book-store-project pull request #5
Opened 2023-07-27 10:00 UTC by Dorcas126

Now that all the functionality is done, I have to add styling.

# Project description

- Add any missing JSX elements to the project (without adding extra functionality)
- The final design should match Zeplin's design (this includes all elements + the same styling)
- Use the CSS rules detailed in Zeplin to style the website.

2023-07-27 10:35 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @Dorcas126👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- Nice UI design. ✔️
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-27 10:35 UTC, thecodechaser commented on src/style/Header.module.css
> +  justify-content: center;
- [ ] Please make sure to increase the left margin for the progress bar, It should be near the `UPDATE PROGRESS` button as on the design.

### Your design

![image](https://github.com/Dorcas126/Book-store-project/assets/83803414/bda3f756-51c0-4704-b1a9-7ae69dc2cb3e)

### Zepline design

![image](https://github.com/Dorcas126/Book-store-project/assets/83803414/f3a944fb-fbfc-4d64-86d4-54591817d6ba)

2023-07-27 10:35 UTC, thecodechaser commented on src/style/Header.module.css
> +  height: 500px;
- [ ] Please make sure the add book section starts on the same line vertically as the book container so please add left margins to it. Please also fix the categories and add book buttons.

### Your design

![image](https://github.com/Dorcas126/Book-store-project/assets/83803414/09e164c0-32a0-406e-a6aa-3f9a7307adee)

### Zeplin design

![image](https://github.com/Dorcas126/Book-store-project/assets/83803414/768b275c-1cb6-4e20-88f5-f2bb6edc1be7)

2023-07-27 12:22 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @Dorcas126,

✔️ Font style follows the design

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-27 12:22 UTC, TedLivist commented on src/routes/Home.js
>  const Home = () => (
- [ ] You have still not implemented the change from the previous reviewer. Kindly compare the designs and stick to it as much as possible

  - The percent score should move closer to the right, next to the Update Progress button
  - The Book form should be made wider to cover the entire length of the container just like the container of the book.

  Your Implementation | Zeplin Design
  :---:|:---:
  ![image](https://github.com/Dorcas126/Book-store-project/assets/36542986/669b93d4-c748-416e-b802-a0b4fa48a43b) | ![image](https://github.com/Dorcas126/Book-store-project/assets/36542986/fc662759-9835-4fd5-b6ef-7306d0357310)

2023-07-28 13:06 UTC, souad988 requested changes
Hi @Dorcas126 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
Good file structure
Create multiple components for reusability 
Overall work is good

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-28 13:06 UTC, souad988 commented on src/components/Book.js
> +      <main className={styles.current}>
[OPTIONAL] main tag is used to wrap the different sections of a page exclud only the header and footer or side navigation bar

2023-07-28 13:06 UTC, souad988 commented on src/style/Header.module.css
> +  padding-right: 90px;
Using a fixed right padding  to align the items is not a good idea , I suggest that you wrap the progress bar and the update progress section in on container and set justify content of their parent wrapper to space-between to get the desired output like the design as mentioned by the previous reviewers 

![Capture d’écran du 2023-07-28 13-54-55](https://github.com/Dorcas126/Book-store-project/assets/59707859/941aa3a9-b7f5-4727-a3f0-d675b62f8141)

if you need further help don't hesitat to ask

2023-07-28 15:50 UTC, mikethreels approved these changes
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good job following the instructions of the previous CR.
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-28 15:59 UTC, merged